name: tsuki_player
description: "A retro MP3 player built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  just_audio: ^0.10.6
  file_picker: ^12.3.0
  media_metadata: ^2.2.2
  saf: ^2.1.2
  shared_preferences: ^2.5.5
  path_provider: ^2.1.6
  audio_service: ^0.18.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  shared_preferences_platform_interface: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/tsuki_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/tsuki_icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/music/
    - assets/icon/

  fonts:
    - family: Minecraftia
      fonts:
        - asset: assets/fonts/Minecraftia-Regular.ttf
